Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,15 +3,9 @@ name: "Build"
 on:
   workflow_dispatch:
   pull_request:
-    branches:
-      - dev
-      - test
-      - main
+    branches: [dev, test, main]
   push:
-    branches:
-      - dev
-      - test
-      - main
+    branches: [dev, test, main]
 
 jobs:
   build:
@@ -19,54 +13,49 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      #1 Checkout Repository
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      #2 Setup Java
       - name: Set Up Java
         uses: actions/setup-java@v3.12.0
         with:
           distribution: 'oracle'
           java-version: '17'
 
-      #3 Setup Flutter
       - name: Set Up Flutter
         uses: subosito/flutter-action@v2
         with:
-          flutter-version: '3.22.2'
+          flutter-version: '3.29.0'
           channel: 'stable'
 
-      #4 Install Dependencies
       - name: Install Dependencies
         run: flutter pub get
 
-      #5 Create .env file
       - name: Create .env file
         run: |
           echo "API_URL=${{ secrets.API_URL }}" > .env
-          cat .env # Optional for debugging
+          cat .env
 
-      #6 Build APK (unsigned release or debug)
-      - name: Build APK
-        run: flutter build apk --release
+      - name: Build APK (Release)
+        run: |
+          flutter build apk --release
+          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
+            echo "APK not found! Build failed."
+            exit 1
+          fi
 
-      #7 Upload Artifacts
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: Releases
-          path: |
-            build/app/outputs/flutter-apk/app-release.apk
+          path: build/app/outputs/flutter-apk/app-release.apk
 
-      #8 Extract Version
       - name: Extract version from pubspec.yaml
         id: extract_version
         run: |
           version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
           echo "VERSION=$version" >> $GITHUB_ENV
 
-      #9 Check if Tag Exists
       - name: Check if Tag Exists
         id: check_tag
         run: |
@@ -75,7 +64,6 @@ jobs:
           else
             echo "TAG_EXISTS=false" >> $GITHUB_ENV
 
-      #10 Modify Tag if it Exists
       - name: Modify Tag
         if: env.TAG_EXISTS == 'true'
         id: modify_tag
@@ -83,10 +71,9 @@ jobs:
           new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
           echo "VERSION=$new_version" >> $GITHUB_ENV
 
-      #11 Create Release
       - name: Create Release
         uses: ncipollo/release-action@v1
         with:
-          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
+          artifacts: build/app/outputs/flutter-apk/app-release.apk
           tag: v${{ env.VERSION }}
           token: ${{ secrets.TOKEN }}
